pipeline:
  input:
    type: "firebase" # Options: "firebase", "csv"
    config:
      collection: "users" # Firestore collection name (only used if input type is "firebase")
      filePath: "./data/input.csv" # Path to the input CSV file (only used if input type is "csv")

  transformations:
    filter:
      - column: "*" # Apply to all numeric columns
        condition: "> 10" # Keep rows where all numeric columns have values > 10
      - column: "age" # Specific filter for column named "age" (if it exists)
        condition: "> 25" # Keep rows with age > 25

    mapping:
      dynamic_mapping: true # Automatically convert column names to lowercase

    aggregation:
      - operation: "sum"
        column: "*" # Sum all numeric columns
        as: "sum_<column>" # Add new columns for sums (e.g., sum_salary)
      - operation: "count"
        column: "*" # Count rows
        as: "row_count"

  output:
    type: "csv" # Options: "firebase", "json", "csv"
    config:
      collection: "users" # Firestore collection name (only used if output type is "firebase")
      filePath: "./data/output.csv" # Path to the output CSV file (only used if output type is "csv" or "json")
