pipeline:
  input:
    type: "firebase"
    config:
      collection: "users" # Firestore collection name

  transformations:
    mapping:
      name_change: "New Name" # Change the name field to "New Name"
      add_field:
        location: "India" # Add a new field called location with value "India"

  output:
    type: "firebase" # Options: "firebase", "json"
    config:
      collection: "users" # Firestore collection name (only used if output type is "firebase")
      filePath: "./data/output.json" # Path to the output JSON file (only used if output type is "json")
