pipeline:
  input:
    type: "json" # Options: "firebase", "json"
    config:
      collection: "users" # Firestore collection name (only used if input type is "firebase")
      filePath: "./data/input1.json" # Path to the input JSON file (only used if input type is "json")

  transformations:
    filter:
      - key: "*" # Apply to all numeric keys
        condition: "> 10" # Keep records where all numeric keys have values > 10
      - key: "age" # Specific filter for key named "age"
        condition: "> 25" # Keep records where age > 25

    mapping:
      dynamic_mapping: true # Automatically convert keys to lowercase

  output:
    type: "firebase" # Options: "firebase", "json"
    config:
      collection: "users" # Firestore collection name (only used if output type is "firebase")
      filePath: "./data/output.json" # Path to the output JSON file (only used if output type is "json")
